#!/usr/bin/env bash
set -e

if [ "$(uname -r | sed -n 's/.*\( *Microsoft *\).*/\1/p')" = "Microsoft"  ]; then
  WSL=true
else
  WSL=false
fi

# Disable sudo prompt
echo "Disabling prompt for sudo"
if ! sudo grep -q "%sudo[[:space:]]ALL=(ALL:ALL) NOPASSWD:ALL" /etc/sudoers >/dev/null 2>&1
then
  echo "%sudo ALL=(ALL:ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers >/dev/null 2>&1 || echo "Failed to edit sudoers file"
fi

# Neovim Repo
echo "Adding PPA for NeoVim"
sudo add-apt-repository ppa:neovim-ppa/stable -y >/dev/null 2>&1 || echo "Failed to add NeoVim PPA"

# Yarn Repo
echo "Adding repo for Yarn"
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - >/dev/null 2>&1 || echo "Failed to add Yarn GPG key"
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null 2>&1 || echo "Failed to add yarn repo"

# Keybase
echo "Installing Keybase"
TEMP_KBS="$(mktemp)"
wget -O "$TEMP_KBS" "https://prerelease.keybase.io/keybase_amd64.deb" >/dev/null 2>&1 || echo "Failed to download keybase"
sudo dpkg --skip-same-version -i "$TEMP_KBS" >/dev/null 2>&1 || echo "Failed to install Keybase"
sudo apt-get -y install -f >/dev/null 2>&1 || echo "Failed to install Keybase deps"
run_keybase > /dev/null 2>&1 || echo "Failed to start Keybase"

# Erlang Repo
echo "Installing Erlang"
TEMP_ERL="$(mktemp)"
wget -O "$TEMP_ERL" "https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb" >/dev/null 2>&1 || echo "Failed to download Erlang"
sudo dpkg --skip-same-version -i "$TEMP_ERL" >/dev/null 2>&1 || echo "Failed to install Erlang"
rm -f "$TEMP_ERL"

# Update apt sources
echo "Updating apt sources"
sudo apt-get -qq -y update

# Get package list to install
echo "Getting packages to install"
PKG_ALL=`echo "$a" | sed '/^||ALL||$/,/^||ENDALL||$/!d;//d' packages` >/dev/null 2>&1 || echo "Failed to load universal packages to install"
PKG_APT=`echo "$a" | sed '/^||APT||$/,/^||ENDAPT||$/!d;//d' packages` >/dev/null 2>&1 || echo "Failed to load apt packages to install"
PACKAGES="$PKG_ALL $PKG_APT"

# Install packages
echo "Installing packages"
sudo apt-get -qq -y install $(echo $PACKAGES | tr '\n' ' ') >/dev/null 2>&1 || echo "Failed to install some packages"

# Start postgres if it was installed
if service --status-all 2>&1 | grep -Fq 'postgresql'
then
  echo "Allowing unauthenticated access to psql"
  echo "host    all             all              0.0.0.0/0                       md5" >> /etc/postgresql/9.5/main/pg_hba.conf
  echo "host    all             all              ::/0                            md5" >> /etc/postgresql/9.5/main/pg_hba.conf

  echo "Starting PostgresQL"
  sudo service postgresql start >/dev/null 2>&1 || echo "Failed to start PostgresQL"
fi

if [ "$WSL" = false ]
then
  # Only on actual Linux, WSL cant do services
  echo "Enabling the PostgresQL service"
  sudo service postgresql enable >/ddev/null 2>&1 || echo "Failed to enable the PostgresQL service"

  # Chromedriver
  echo "Installing chromedriver"
  sudo apt-get -qq -y install chromium-browser chromium-chromdriver >/dev/null 2>&1 || echo "Failed to install chromedriver"
  sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver >/dev/null 2>&1 || echo "Failed to symlink chromium-chromedriver to chrome-chromedriver"
else
  # WSL Helpers symlinks
  echo "Symlinking WSL specific files"
  mkdir -p ~/bin

  echo "Linking Chromedriver"
  sudo rm -rf ~/bin/chromedriver > /dev/null 2>&1
  ln -sf $PWD/dotfiles/bin/chromedriver ~/bin/chromedriver

  echo "Linking MSBuild"
  sudo rm -rf ~/bin/msbuild > /dev/null 2>&1
  ln -sf $PWD/dotfiles/bin/msbuild ~/bin/msbuild

  echo "Linking wsl-browser-bridge"
  sudo rm -rf ~/bin/wsl-browser-bridge > /dev/null 2>&1
  ln -sf $PWD/dotfiles/bin/wsl-browser-bridge ~/bin/wsl-browser-bridge

  echo "Linking wslpath"
  sudo rm -rf ~/bin/wslpath > /dev/null 2>&1
  ln -sf $PWD/dotfiles/bin/wslpath ~/bin/wslpath

  # Install stuff on the Windows-side
  echo "Installing Windows programs"
  pushd /mnt/c >/dev/null 2>&1

  cmd.exe /c "if not exist Workspace\\Tools\\Chromedriver mkdir Workspace\\Tools\\Chromedriver" >/dev/null 2>&1 || echo "Failed to creare dir for Chromedriver"
  cmd.exe /c "if not exist Workspace\\Tools\\Wsltty\\bin mkdir Workspace\\Tools\\Wsltty\\bin" >/dev/null 2>&1 || echo "Failed to create dir for Wsltty"
  cd /mnt/c/Workspace/Tools

  # Chromedriver
  echo "Downloading Chromedriver"
  TEMP_NGT="$(mktemp)"
  wget -O "$TEMP_NGT" "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" >/dev/null 2>&1 || echo "Failed to download nuget.exe"
  mv "$TEMP_NGT" /mnt/c/Workspace/Tools/nuget.exe || echo "Failed to move buget.exe to Tools folder"
  cmd.exe /c "nuget.exe install Selenium.WebDriver.ChromeDriver -ExcludeVersion" >/dev/null 2>&1 || echo "Failed to download chromedriver from nuget"
  mv Selenium.WebDriver.ChromeDriver/driver/win32/chromedriver.exe Chromedriver/ || echo "Failed to move Chromedriver to Tools folder"

  # Wsltty
  echo "Installing Wsltty"
  sudo apt-get -y install p7zip-full p7zip-rar >/dev/null 2>&1 || echo "Failed to download 7z for extracting wsltty"
  TEMP_WSL="$(mktemp -d)"
  wget -O "$TEMP_WSL/wsltty.exe" "https://github.com/mintty/wsltty/releases/download/1.8.3.2/wsltty-1.8.3.2-install.exe" >/dev/null 2>&1 || echo "Failed to download Wsltty"
  7z e $TEMP_WSL/wsltty.exe -o/mnt/c/Workspace/Tools/Wsltty/bin cygwin1.dll cygwin-console-helper.exe mintty.exe wslbridge.exe wslbridge-backend -y >/dev/null 2>&1 || echo "Failed to extract Wsltty"

  # Cleanup
  echo "Cleaning up"
  rm -r $TEMP_WSL
  rm nuget.exe
  rm -r Selenium.WebDriver.ChromeDriver

  popd >/dev/null 2>&1

  echo "Copying Wsltty dotfiles to Wsltty folder"
  cp dotfiles/wsltty/* /mnt/c/Workspace/Tools/Wsltty -r

  echo "Creating shortcut to Wsltty on Windows Start Menu"
  powershell.exe -Command 'robocopy "C:\Workspace\Tools\Wsltty" "$env:APPDATA\Microsoft\Windows\Start Menu\Programs" wsl-terminal.lnk' >/dev/null 2>&1 || echo "Failed to copy shortcut"
  powershell.exe -Command '(New-Object -ComObject shell.application).Namespace("$env:APPDATA\Microsoft\Windows\Start Menu\Programs").parsename("wsl-terminal.lnk").invokeverb("pintostartscreen")' >/dev/null 2>&1 || echo "Failed to pin shortcut to Start Menu"
fi
